### ISSUE TITLE
Syntax Error in print()

### ISSUE THREAD

**Issue by ktkirk** [architv/harvey#1]
$ python harvey/harvey.py list
{license_name} [{license_code}]
Traceback (most recent call last):
  File "harvey/harvey.py", line 152, in <module>
    main()
  File "harvey/harvey.py", line 142, in main
    _get_licences()
  File "harvey/harvey.py", line 64, in _get_licences
    print("{license_name} [{license_code}]").format(license_name=licenses[license], license_code=license)
AttributeError: 'NoneType' object has no attribute 'format'

Fix:
print("{license_name} [{license_code}]".format(license_name=licenses[license],                  license_code=license))

**Comment by architv** [comment]
Thanks @ktkirk ! Fixed with a6babfa5797ce902e68d3620026f27384f41573
