### ISSUE TITLE
Colorama not working on Windows

### ISSUE THREAD

**Issue by thurask** [architv/harvey#3]
Less of a bug and more of a tip.

By default, most of app works well on Windows (Windows 10 over here) except for colorama. ANSI escape  sequences show up in terminal instead of color.

I fixed this by building https://github.com/adoxa/ansicon from source and installing. Works great now.

![colorama](https://cloud.githubusercontent.com/assets/7698858/10897931/b1ee219c-8193-11e5-96d1-27c00ccab779.png)

**Comment by architv** [comment]
I couldn't test the app on windows. Should I add it in the README to install [ansicon](https://github.com/adoxa/ansicon) from the source?

**Comment by thurask** [comment]
Sure, although I believe that downloading the latest packaged version of ansicon from the releases page would work just as fine.

**Comment by architv** [comment]
Thanks! I added the [instructions](https://github.com/architv/harvey#note) in README.
